{
 "title": "envios-ativos",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Instancia", "query": { "query": "label_values(exported_job)" } }
  ]
 },
 "panels": [
  {
   "title": "Enviados",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$SENT-$DELIVERED", "type": "math" }
   ]
  },
  {
   "title": "Recebidos",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$DELIVERED-$READ", "type": "math" }
   ]
  },
  {
   "title": "Lidos",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "message_outbound_status_read{exported_job=\"$Instancia\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$DELIVERED-$READ", "type": "math" },
    { "expression": "$SENT-$DELIVERED", "type": "math" },
    { "expression": "$STORED-$SENT", "type": "math" },
    {
     "expr": "message_outbound_status_read{exported_job=\"$Instancia\"}",
     "legendFormat": "Lidos"
    },
    {
     "expr": "message_outbound_status_error{exported_job=\"$Instancia\"}",
     "legendFormat": "Falhas"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$STORED+$ERROR", "type": "math" }
   ]
  },
  {
   "title": "Falhas",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "message_outbound_status_error{exported_job=\"$Instancia\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Registros e Falhas",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "message_outbound_status_stored{exported_job=\"$Instancia\"}",
     "legendFormat": "Registrados"
    },
    {
     "expr": "message_outbound_status_error{exported_job=\"$Instancia\"}",
     "legendFormat": "Falhas"
    }
   ]
  }
 ]
}